version: 2

run:
  timeout: 5m
  tests: true
  issues-exit-code: 1
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - gocritic
    - gocyclo
    - bodyclose
    - misspell
    - unparam
    - whitespace
    - godot
    # - revive

settings:
  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: indent-error-flow
      - name: unreachable-code
      - name: blank-imports
      - name: context-as-first-argument
      - name: cognitive-complexity
        arguments: [15]

  gocritic:
    enabled-checks:
      - appendAssign
      - boolExprSimplify
      - rangeValCopy
      - ruleguard

  gosec:
    excludes:
      - G104

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocyclo

    - path: main\.go
      text: "forgetting to check returned errors"
      linters:
        - errcheck

    - linters:
        - revive
      text: "package-comments"
    - linters:
        - revive
      text: "exported"
